# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ksgh_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_kshc(object):
    def setupUi(self, kshc):
        kshc.setObjectName("kshc")
        kshc.setEnabled(True)
        # kshc.resize(428, 176)
        kshc.setFixedSize(428, 176)
        kshc.setMaximumSize(QtCore.QSize(428, 176))
        self.frame = QtWidgets.QFrame(kshc)
        self.frame.setGeometry(QtCore.QRect(0, 0, 431, 181))
        self.frame.setStyleSheet("\n"
"background-color: rgb(232, 232, 232);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(70, 110, 121, 41))
        self.pushButton.setStyleSheet("border: 1px solid;\n"
"          background-color: transparent;\n"
"          text-transform: uppercase;\n"
"          font-size: 14px;\n"
"          padding: 10px 20px;\n"
"          font-weight: 300;\n"
"color: white;\n"
"          border: 0;\n"
" background-color: #4cc9f0;\n"
"          -webkit-box-shadow: 10px 10px 99px 6px rgba(76,201,240,1);\n"
"          -moz-box-shadow: 10px 10px 99px 6px rgba(76,201,240,1);\n"
"          box-shadow: 10px 10px 99px 6px rgba(76,201,240,1);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(270, 110, 121, 41))
        self.pushButton_2.setStyleSheet("border: 1px solid;\n"
"          background-color: transparent;\n"
"          text-transform: uppercase;\n"
"          font-size: 14px;\n"
"          padding: 10px 20px;\n"
"          font-weight: 300;\n"
"color: white;\n"
"          border: 0;\n"
" background-color: #4cc9f0;\n"
"          -webkit-box-shadow: 10px 10px 99px 6px rgba(76,201,240,1);\n"
"          -moz-box-shadow: 10px 10px 99px 6px rgba(76,201,240,1);\n"
"          box-shadow: 10px 10px 99px 6px rgba(76,201,240,1);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(10, 40, 71, 51))
        self.label.setStyleSheet("font: 10pt \"黑体\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setEnabled(True)
        self.label_2.setGeometry(QtCore.QRect(210, 40, 71, 51))
        self.label_2.setStyleSheet("font: 10pt \"黑体\";")
        self.label_2.setObjectName("label_2")
        self.comboBox_dq = QtWidgets.QComboBox(self.frame)
        self.comboBox_dq.setGeometry(QtCore.QRect(80, 51, 111, 31))
        self.comboBox_dq.setObjectName("comboBox_dq")
        self.comboBox_gh = QtWidgets.QComboBox(self.frame)
        self.comboBox_gh.setGeometry(QtCore.QRect(280, 50, 111, 31))
        self.comboBox_gh.setObjectName("comboBox_gh")

        self.retranslateUi(kshc)
        QtCore.QMetaObject.connectSlotsByName(kshc)

    def retranslateUi(self, kshc):
        _translate = QtCore.QCoreApplication.translate
        kshc.setWindowTitle(_translate("kshc", "快速换床"))
        self.pushButton.setText(_translate("kshc", "确认"))
        self.pushButton_2.setText(_translate("kshc", "取消"))
        self.label.setText(_translate("kshc", "当前床位："))
        self.label_2.setText(_translate("kshc", "更换床位："))
        # self.comboBox_dq.addItem("--请选择--")
        self.comboBox_gh.addItem("--请选择--")
